### ISSUE TITLE
Possible features

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/PredictPokemon-2#2]
- Density of population --> Hypotesis: The more people living in an area, the more pokemon
- 3G quality/coverage
- Sales of smartphones in a certain area/country

**Comment by goldbergtatyana** [comment]
Hi @bensLine @semioniy @Aurel-Roci ! How are you getting along with the machine learning tutorial? Is all clear and you have a good feeling on how to operate weka?

**Comment by semioniy** [comment]
Hi, @goldbergtatyana. Not really good. It's about clear what you said in tutorial, but it's hard to go beyond that toward real understanding what it does and how it does it. Still trying to figure out though.

**Comment by semioniy** [comment]
@bensLine, @Aurel-Roci, how do you think, maybe we should consider the level of the trainer as well?
This data won't probably be really hard to gather, but maybe it influences, how common/ rare are the pokemon the one finds?

**Comment by Aurel-Roci** [comment]
@semioniy from what I have found from friends that play the game, at least for them it depends on the area, not on the level they have. The only thing that differs depending on the level is the CP the pokemon have.

**Comment by Aurel-Roci** [comment]
Hi, @goldbergtatyana the tutorial was good, and since I was there I got a better understanding of it. But what I am having problems with now, is using the dummy data provided here [https://github.com/gyachdav/pokemongo](url); how to write them in an .arff file to test them on weka. Anyway I can get some help with that?

**Comment by bensLine** [comment]
Hi @goldbergtatyana, sorry for the delay I was on holidays. Thanks for the tutorial it was great for refreshing, I used Weka already.

However, the way I understood the project is that the TLN predictions will be query based and there are two use cases:
- User is at location A and want's to know which Pokemon appear in the next e.g. 30min. So we'll actually just predict the name, as location and time are given.
- User wants to know where Pokemon X appears -> time and location are unknown, only the name is known.
  Is this correct or are there other queries?

@Aurel-Roci I committed a script to parse the data into an .arff file (https://github.com/PokemonGoers/PredictPokemon-2/tree/feature/test_data). It's very basic and might not be good JS practice - haven't used JS before :p
I did not extract all data from the JSON file, e.g. id of the entry, as it is unique, or user id, as I don't think it influences the appearance of Pokemon. However, feel free to adapt the script.

I also added one more feature: the distance to a reference point for testing purposes.
I wanted to extract time features too, but most of the timestamps in the dummy data are all within a 5min window, so we cannot really use that data to find appropriate time intervals.
However, we could slice the day into intervals and then use them as features too, e.g. 3h slices. Maybe some Pokemon appear more likely in the evening.

@semioniy concerning the trainer level, I would go with Aurel's answer

@sacdallago the hypothesis sounds good, we have to research if we can find a data source to extract features for that. I did not yet look into it.

**Comment by sacdallago** [comment]
@bensLine you commited directly on develop. Not good. Please use GitFlow/Feature model!!! Read some of the first announcement emails!.. From now on, we deduct points to who commits without opening PRs

**Comment by goldbergtatyana** [comment]
Hi Machine Learners! Sorry, I was absent yesterday, but now I am back :wave:

@bensLine it is great how you summarized the ML problem. Really, good job!

At the moment I can also think of only these two queries. However, for the second one we can also set a time frame of say 5 minutes or half an hour. Then only the location will be unknown.

@Aurel-Roci et al.: did you get the arff file from the dummy data? did you already try apply any of the ML algorithms on it?

**Comment by bensLine** [comment]
Thanks @goldbergtatyana, it is nice to have the time frame for the second query.

Here are some ideas about features:
1. network coverage
2. Population
3. Location Popularity
4. Weather (perception, temp, sun hours, ..)
5. Sunrise sunset (time before/after)
6. terrain (water, mountains, ...)

However, those features usually rely on an API to get some data. But most of the APIs allow only a limited amount of requests per day. I assume that those limits could be reached and our IP and/or API key get blocked. Should we ignore this or are there other ideas(several ips/keys, ...)?

What do you think about the features, are they good, should we integrate them?
1. we did not yet find a good solution. http://www.sensorly.com/ and http://developer.opensignal.com/networkrank/ provide information but best would be to create an own (offline) map out of their data, which is probably a lot of work.
2. Should be easier to obtain e.g. from https://query.wikidata.org/. However, we would need several requests to resolve lat/lon to a location and then to the population of the referred city if there is one..
3. With the consideration of the previous text, it might be better to have a popularity measure for locations. However, how to calculate the popularity from lat/lon needs to be further investigated. Do you think it would make sense?
4. For weather data, we could use http://openweathermap.org but the API only provides current weather information for free. So we cannot enrich historical data (e.g. data set from team A or queries for past dates). If the data from A provides the features already it should be fine (queries with past dates would be neglected). However, here we'll have the problem with the API request limit.
5. Might be already available through weather data. Otherwise, another source needs to be found.
6. The terrain for lat/lon can be used to specify if water is close or not and other types. To obtain the data the overpass API for open street maps can be used. http://overpass-turbo.eu/

So, what do you think about the different features/data sources? Which one should we implement and how should we deal with the query limits?

Furthermore, should we actually use lon and lat directly as features? I read that people rasterize the earth surface and use cell ids instead. E.g. by using Google's S2 library cells with up 1 cm² can be created. However, this would end up in a huge value range even with large cells. Anyway, we would not have the continues lat/lon values anymore and could express the location as a single feature. S2 also preserves spatial locality.
But again, not sure if it's worth to implement that. is it a good idea? There are JS ports of the library. One is actually supposed to be used by pokemon go itself. https://github.com/Daplie/s2-geometry.js

And related to that: we consider the whole globe, right? Or can we focus on a smaller area, e.g. only Europe?

**Comment by goldbergtatyana** [comment]
Great points @bensLine!!!

Let us get back to you shortly about the features you suggested. 

As to Google's S2 library: it looks like something what we exactly need! Using a grid of 1cm2 is prob too much for us. What we rather have in mind is the following:

Query 1: a user opens an app and we predict a Pokemon at every 200m (or 500m or 1km - we'll need to see which one performs best with out ml tool) within a square of 10 x 10 km. So, a user can zoom out and move the map within a square of 10 x 10 km without a need for our ml to redo a calculation. If a user moves out from this square, then we'll need to run our ml method again for a new 10 x 10 km square.

Query 2: we rasterize the earth surface at a very broad grained level (eg in squares of 100km in length, maybe even more) and then we predict pokemons globe-wide.

For both queries we run predictions for the next 30mins or hour (again, dependent on where ml tool performs best) and the pipeline should be the same.

**Comment by goldbergtatyana** [comment]
@gyachdav

**Comment by gyachdav** [comment]
@bensLine the features you're suggesting sound promising. However at this point I would recommend trying to simplify then over stretching yourself. Check out this simple tutorial first - http://tutorials.pluralsight.com/big-data/use-a-data-analytics-tool-to-predict-where-the-pokemon-are-going-to-appear

The only additional features beyond TLNs are weather related features and proximity to grass, water, buildings. 

I would suggest you:
1. generate an arff file based on these features. 
2. use the S2 library to get a cell ID from the lon/lat pairs. you probably want to focus on a set of defined cells as a start. 
3.  predict and benchmark your learner on this input set
4. report  your outcome to us. 

Once we mastered working with spatial data and predictions we can move on to test other features. But let's get the basics first!

**Comment by bensLine** [comment]
@gyachdav @goldbergtatyana thanks for the advice! We'll look into that.

**Comment by goldbergtatyana** [comment]
As a proof of principle we can train a prediction method already now based on dummy data. Task #1: upload here a working arff file

**Comment by goldbergtatyana** [comment]
Hey all,

Let's have the features summarized here again:
1. Location 
2. Weather (e.g. temperature, humidity, atmospheric pressure, wind)
3. Terrain (e.g. proximity to water, gras, buildings)
4. Proximity to a gym (within 200 meters, 1 kilometer and 5 kilometers)
5. Co-occurrence to each of ~150 pokemons ever spotted in the radius of 200 meters, 1 kilometer and 5 kilometers 
6. Co-occurrence to each of ~150 pokemons spotted within the last hour in the radius of 200 meters, 1 kilometer and 5 kilometers 
7. Population size

And their descriptions:
1. I would make 3 features out of it (long, lat and the s2 ID)
2. These will be nominal features 
3. These I imagine to be binary features 
4. Please provide here 3 binary features. Provide yes if the location is within 200 meters to a gym and no otherwise. Do the same also for the radius of 1 and 5 km.
5. Altogether there are 151 pokemons, which should result in 453 features. Provide for each Pokemon a yes if a Pokemon has ever been spotted within 200 meters to a location and no otherwise. Do the same for the radius of 1 and 5 km.
6. Similar to 5.
7. Here anything can work, either population size of the area or the number of buildings or just a classification of whether the area has >10 mio inhabitants, 1-10mio, 200-500k, <200k

Once we have all these features, we'll do feature selection to identify those that are most contributing for the prediction. Now is the goal to come up with as many as possible candidate features. Feel free to suggest more features and add them to the list. 

Please assign each of the points we have so far in the list to a different member of your group. Reach out to us for help :)

**Comment by gyachdav** [comment]
this table might be of interest

http://pokemongohub.net/pokemon-go-spawn-rate/

**Comment by bensLine** [comment]
@gyachdav that's definitely interesting, thanks! do you know how much time it takes from one spawn to another?  I'm not sure how to map the occurrence rate to time intervals. Probably not straight forward :p

@goldbergtatyana thanks for the list :) feature 5. and 6. however, are not yet clear. We discussed them in our team a bit, and it seems like this would require a classifier for each location (at least cell).

E.g. feature 5: if we add 'co-occurrence of pokemons ever spotted in a radius' we need to refer to a location. As a result, we end up with different data sets for all locations.
And for feature 6 we have to create a new classifier constantly, as we only consider sights within the last hour according to the request timestamp.

This seems like we will calculate features 5. and 6. for every request (consisting out of location and time). Is this right? If so, as a result, we have to recalculate feature 5. and 6. for the entire training set and then retrain the SVM for every request. This would take some time I guess.. is this feasible or do I get something wrong?

**Comment by goldbergtatyana** [comment]
Hi @bensLine! The idea is actually a much simpler one. :)

Let's discuss it with you and your team members tomorrow on Skype, as suggested, and summarize the tasks for features 5 & 6 tomorrow again.

**Comment by gyachdav** [comment]
@bensLine what we know is that they used 100M data points over a period of one week. so if Pidgey appeared 1598 per 10k sightings it should roughly appear ~1.6M times in the 10M dataset or ~1.6 in one week. Roughly every 1/3 of a second. Main problem is of course that spawns are not spread evenly over time (as the spawn most active column suggests). So now we need to figure out what is the spawn distro for Pidgey's. I'm pretty sure you can get this distro from the API project A provides. Then instead of dividing 1.6M/600k seconds a week just distribute those sightings across the number of seconds you back out of the distro (make sure you scale this number to one week). That should give you your answer.

**Comment by semioniy** [comment]
@goldbergtatyana, @gyachdav, if I understand right, these are all features to be implemented. Is that right?
1.  Location in  form of: 
   1. a.  Lat/ long
   2. b.  S2 Cell #5 
   3. c.  Timezone (for time parsing) 
2.  Time:
   1. a.  UTC
   2. b.  Local time in #8  
           2. b. i. Classical form  
           2. b. ii.  Minutes from midnight  
           2. b. iii. Part of the day (morning, noon, afternoon, evening etc.)  
           2. b. iv. Time before/ after sunrise/ sunset  
3.  Weather: #6 
   1. a.  Temperature
   2. b.  Rain/ sunny etc.
   3. c.  Barometer
   4. d.  Humidity
   5. e.  Wind (Force, direction)
4.  Terrain specifications: #7
   1. a.  Grass/ asphalt/ building
   2. b.  Proximity to water
   3. c.  Maybe altitude (is it mountain?)
5.  Proximity to a jym
   1. a.  Source: map of jyms/ ingress map?
   2. b.  Proximity in meters as nominal attribute (100/200/300/500/750/1000m)
6.  Co-occurrence to each of ~150 pokemons ever spotted in the radius of 200/1000/5000m
7.  Co-occurrence to each of ~150 pokemons spotted within the last hour in the radius of 200/1000/5000m
8.  Population size (of the city)
9.  Population density in that area (if we find a source)
10. Same for location popularity (network usage as indicator?)
11. Same for network coverage
12. Split pokemons by their type (fire/ grass)

**Comment by gyachdav** [comment]
You currently have no descriptive features of the Pokemon so I would add:
1. average CP
2. Average HP
3. Weight
4. Height
5. Type of attacks (you can have individual binary feature for each attack type)
6. Weakness
   Any other descriptive feature. 

@goldbergtatyana what do you think? We can alternatively just use the pokemonId as a representation of all those descriptive features but maybe expanding the feature set is worthwhile here?

**Comment by goldbergtatyana** [comment]
Thanks @semioiy for the list! It looks complete to me. Can you please make a todo list out of it where we can strike through items that are already completed. It would be very nice to have such a list for an overview of what is done. 

@gyachdav: the descriptive features for a Pokemon that we will predict won't be available (we won't know it's height and weight) and if we limit ourselves for predicting location of Pokemon A with a height X then we will limit ourselves too much. Rather we want to predict A of all heights. So, I think these descriptive features are not of a big help for our prediction task.

**Comment by gyachdav** [comment]
@goldbergtatyana not sure I understood that last part. The descriptive features of a pokemon are available to us as much as the pokemonID is available to us. If we predict a pokemon name to appear at a certain time and location then we're also predicting what height,weight, avg CP etc it will be.

**Comment by semioniy** [comment]
# //TODO
- [x] **1.  Location in  form of:** 
- [x] <del> ---> a. Lat/ long</del>
- [x] ---> b.   S2 Cell #5 
- [x] <del>---> c.  Timezone (for time parsing)</del> not needed, part of time features
- [x] **2.  Time:**
- [x] <del> ---> a. UTC</del>
- [x] ---> b.   Local time in #8
- [x] <del>-------> _i.     Classical form_</del>
- [x] -------> _ii. Minute, hour, month, year
- [x] <del>-------> _ii.    Minutes from midnight_</del>
- [x] -------> _iii.   Part of the day (morning, noon, afternoon, evening etc.)_ **as numeric**
- [x] -------> _iv.   Time before/ after sunrise/sunset_ from cell id
- [x] **3.  Weather: #6** all data for cell id
- [x] ---> a.   Temperature
- [x] ---> b.   Rain/ sunny etc.
- [x] ---> c.   Barometer
- [x] ---> d.   Humidity
- [x] ---> e.   Wind (Force, direction)
- [x] **4.  Terrain specifications: #7**
- [x] ---> a.   Grass/ asphalt/ building
- [x] ---> b.   Proximity to water
- [ ] <del>---> c.  Maybe altitude (is it mountain?)</del>
- [x] **5.  Proximity to a gym** 
- [x] ---> a.   Source: read out from big data dump
- [x] ---> b.   is in proximity? as binary feature for (100/200/300/500/750/1000m)
- [x] **6.  Co-occurrence to each of ~150 pokemons #29**
- [ ] <del>---> a.  ever spotted in the radius of 200/1000/5000m</del>
- [x] ---> b.   spotted within the last hour in the radius of 90m
- [ ] **7.  Population #28** data source needs to be found
- [ ] ---> a.   Population size (of the city)
- [x] ---> b.   Population density in that area
- [ ] <del>**8. Same for location popularity** (network usage as indicator?)</del>
- [ ] <del>**9. Same for network coverage**</del>
- [x] **10. Split pokemons by their type (fire/ grass) #27** not needed to predict pokemons by date and time
- [x] **11. Proximity to a Pokestop** 
- [x] ---> a.   Source: read out from big data dump
- [x] ---> b.   is in proximity? as binary feature for (100/200/300/500/750/1000m)

**Comment by goldbergtatyana** [comment]
We agreed with @gyachdav to have the features describing a Pokemon as a simple lookup. No need to implement height, weight and other descriptive features for our ml model.

**Comment by juanmirocks** [comment]
**Gyms**, possible more features (as long as it's possible to extract from data API):
- [ ] CP of highest-ranking pokemon (maximum CP)
- [ ] CP sum of all stacked pokemons
- [ ] Number of pokemon stacked
- [ ] Team: red, blue, yellow -- (**Valor** team is the best)

We know that Gym values change often. However, the highest ranking of the last winning team can give us an estimation of the level of trainers in the area.

**Pokestops**, possible more features (as long as it's possible to extract from data API):
- [x] yes/no 3 binary features for whether a sponsored pokestop is nearby (again, 200m, 1km, or 5km) -- AFAIK sponsored pokestops are still only available in Japan, but that's already a huge market
- [x] yes/no binary for proximity of 200 m to a pokestop (analogous to gym feature)
- [x] yes/no binary for proximity of 1km to a pokestop (analogous to gym feature)
- [x] yes/no binary for proximity of 5km to a pokestop (analogous to gym feature)
- [x] Nominal value of minimum distance to a pokestop (analogous to gym feature)

**Lures**, possible more features (as long as it's possible to extract from data API):
- [ ] Number of lures 200m nearby
- [ ] Number of lures 1km nearby
- [ ] Number of lures 5m nearby

We know that lures disappear fast. Yet, I think we could get typical areas where lures are common == many pokemon trainers == many pokemons (related to pokemonbs)

Please pokemon go experts :-) think of more possible features related to gyms, pokestops, and lures -- Or anything else you think it's relevant to get the presence of pokemon

**Comment by MatthiasBaur** [comment]
All features in the first list have been implemented.
Pokestops have been implemented similarily to gyms as binary features based on several distances.
The next step is to cut down the number of features again. I will reference the corresponding issue shortly.

**Comment by MatthiasBaur** [comment]
#62
